[server]
mode = ""
port = ""
version = ""

[mongo.local]
[mongo.local.app]
Host = "mongodb://localhost:27017"
User = "windowshyun"
Pass = "hyun!"

[mongo.local.api]
Host = "mongodb://localhost:27017"
User = "windowshyun"
Pass = "hyun!"

[mongo.local.common]
Host = "mongodb://localhost:27017"
User = "windowshyun"
Pass = "hyun!"

[mongo.develop]
[mongo.develop.app]
Host = "mongodb://192.168.6.16:27017"
User = "windowshyun"
Pass = "hyun!"

[mongo.develop.api]
Host = "mongodb://192.168.6.16:27017"
User = "windowshyun"
Pass = "hyun!"

[mongo.develop.common]
Host = "mongodb://192.168.6.16:27017"
User = "windowshyun"
Pass = "hyun!"

[mysql]
[mysql.local]
Host = "localhost"
User = "windowshyun"
Pass = "hyun!"
Port = "3306"
DB = "history"

[mysql.develop]
Host = "192.168.6.16"
User = "windowshyun"
Pass = "hyun!"
Port = "3306"
DB = "history"

[redis]
[redis.local]
host = "localhost"
port = "6379"
pass = "hyun!"

[redis.develop]
host = "192.168.6.16"
port = "6379"
pass = "hyun!"

[log]
level = "debug" # debug or info
fpath = "./logs" # 로그가 생성될 경로 : ./logs
maxSize = 2000    # 2g : megabytes
maxAge = 7        # 7days
maxBackup = 7    # number of log files
compress = false # backup compress

[secretKey]
APPSecretKey = "259238489399363557367989578295"
APISecretKey = "653394399872486779676547347875"
CommonSecretKey = "523543486863499536562376547399"